<?php

namespace App\Enums;

enum VisualizationSource: string
{
    case AutoGenerated = 'auto_generated';
    case UserCreated = 'user_created';
    case AiRecommended = 'ai_recommended';

    public function label(): string
    {
        return match ($this) {
            self::AutoGenerated => 'Généré automatiquement',
            self::UserCreated => 'Créé manuellement',
            self::AiRecommended => 'Recommandé par l\'IA',
        };
    }
}
